CREATE TABLE COURSE (cid int, cname varchar(50))
INSERT INTO COURSE (cid, cname) VALUES(1,'Music')
INSERT INTO COURSE (cid, cname) VALUES(2,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(3,'Art')
INSERT INTO COURSE (cid, cname) VALUES(4,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(5,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(6,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(7,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(8,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(9,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(10,'History')
INSERT INTO COURSE (cid, cname) VALUES(11,'German')
INSERT INTO COURSE (cid, cname) VALUES(12,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(13,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(14,'History')
INSERT INTO COURSE (cid, cname) VALUES(15,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(16,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(17,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(18,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(19,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(20,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(21,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(22,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(23,'Science')
INSERT INTO COURSE (cid, cname) VALUES(24,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(25,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(26,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(27,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(28,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(29,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(30,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(31,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(32,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(33,'German')
INSERT INTO COURSE (cid, cname) VALUES(34,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(35,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(36,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(37,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(38,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(39,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(40,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(41,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(42,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(43,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(44,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(45,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(46,'Art')
INSERT INTO COURSE (cid, cname) VALUES(47,'French')
INSERT INTO COURSE (cid, cname) VALUES(48,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(49,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(50,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(51,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(52,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(53,'Music')
INSERT INTO COURSE (cid, cname) VALUES(54,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(55,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(56,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(57,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(58,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(59,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(60,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(61,'German')
INSERT INTO COURSE (cid, cname) VALUES(62,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(63,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(64,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(65,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(66,'Science')
INSERT INTO COURSE (cid, cname) VALUES(67,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(68,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(69,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(70,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(71,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(72,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(73,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(74,'Health')
INSERT INTO COURSE (cid, cname) VALUES(75,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(76,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(77,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(78,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(79,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(80,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(81,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(82,'History')
INSERT INTO COURSE (cid, cname) VALUES(83,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(84,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(85,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(86,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(87,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(88,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(89,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(90,'Health')
INSERT INTO COURSE (cid, cname) VALUES(91,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(92,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(93,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(94,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(95,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(96,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(97,'History')
INSERT INTO COURSE (cid, cname) VALUES(98,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(99,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(100,'Mathematics')