CREATE TABLE COURSE (cid int, cname varchar(50))
INSERT INTO COURSE (cid, cname) VALUES(1,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(2,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(3,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(4,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(5,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(6,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(7,'History')
INSERT INTO COURSE (cid, cname) VALUES(8,'Music')
INSERT INTO COURSE (cid, cname) VALUES(9,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(10,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(11,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(12,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(13,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(14,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(15,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(16,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(17,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(18,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(19,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(20,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(21,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(22,'History')
INSERT INTO COURSE (cid, cname) VALUES(23,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(24,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(25,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(26,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(27,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(28,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(29,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(30,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(31,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(32,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(33,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(34,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(35,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(36,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(37,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(38,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(39,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(40,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(41,'History')
INSERT INTO COURSE (cid, cname) VALUES(42,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(43,'Health')
INSERT INTO COURSE (cid, cname) VALUES(44,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(45,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(46,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(47,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(48,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(49,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(50,'History')