CREATE TABLE COURSE (cid int, cname varchar(50))
INSERT INTO COURSE (cid, cname) VALUES(1,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(2,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(3,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(4,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(5,'French')
INSERT INTO COURSE (cid, cname) VALUES(6,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(7,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(8,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(9,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(10,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(11,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(12,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(13,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(14,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(15,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(16,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(17,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(18,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(19,'Science')
INSERT INTO COURSE (cid, cname) VALUES(20,'Art')
INSERT INTO COURSE (cid, cname) VALUES(21,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(22,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(23,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(24,'History')
INSERT INTO COURSE (cid, cname) VALUES(25,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(26,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(27,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(28,'German')
INSERT INTO COURSE (cid, cname) VALUES(29,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(30,'French')
INSERT INTO COURSE (cid, cname) VALUES(31,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(32,'Health')
INSERT INTO COURSE (cid, cname) VALUES(33,'Health')
INSERT INTO COURSE (cid, cname) VALUES(34,'Music')
INSERT INTO COURSE (cid, cname) VALUES(35,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(36,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(37,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(38,'Art')
INSERT INTO COURSE (cid, cname) VALUES(39,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(40,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(41,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(42,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(43,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(44,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(45,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(46,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(47,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(48,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(49,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(50,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(51,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(52,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(53,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(54,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(55,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(56,'Music')
INSERT INTO COURSE (cid, cname) VALUES(57,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(58,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(59,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(60,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(61,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(62,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(63,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(64,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(65,'Health')
INSERT INTO COURSE (cid, cname) VALUES(66,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(67,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(68,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(69,'Art')
INSERT INTO COURSE (cid, cname) VALUES(70,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(71,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(72,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(73,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(74,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(75,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(76,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(77,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(78,'History')
INSERT INTO COURSE (cid, cname) VALUES(79,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(80,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(81,'Music')
INSERT INTO COURSE (cid, cname) VALUES(82,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(83,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(84,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(85,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(86,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(87,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(88,'Music')
INSERT INTO COURSE (cid, cname) VALUES(89,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(90,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(91,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(92,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(93,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(94,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(95,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(96,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(97,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(98,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(99,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(100,'Health')
INSERT INTO COURSE (cid, cname) VALUES(101,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(102,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(103,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(104,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(105,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(106,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(107,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(108,'Art')
INSERT INTO COURSE (cid, cname) VALUES(109,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(110,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(111,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(112,'Music')
INSERT INTO COURSE (cid, cname) VALUES(113,'Music')
INSERT INTO COURSE (cid, cname) VALUES(114,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(115,'German')
INSERT INTO COURSE (cid, cname) VALUES(116,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(117,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(118,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(119,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(120,'Music')
INSERT INTO COURSE (cid, cname) VALUES(121,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(122,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(123,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(124,'Science')
INSERT INTO COURSE (cid, cname) VALUES(125,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(126,'Music')
INSERT INTO COURSE (cid, cname) VALUES(127,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(128,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(129,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(130,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(131,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(132,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(133,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(134,'French')
INSERT INTO COURSE (cid, cname) VALUES(135,'Art')
INSERT INTO COURSE (cid, cname) VALUES(136,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(137,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(138,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(139,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(140,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(141,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(142,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(143,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(144,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(145,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(146,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(147,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(148,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(149,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(150,'German')
INSERT INTO COURSE (cid, cname) VALUES(151,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(152,'History')
INSERT INTO COURSE (cid, cname) VALUES(153,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(154,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(155,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(156,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(157,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(158,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(159,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(160,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(161,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(162,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(163,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(164,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(165,'Art')
INSERT INTO COURSE (cid, cname) VALUES(166,'Health')
INSERT INTO COURSE (cid, cname) VALUES(167,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(168,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(169,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(170,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(171,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(172,'Art')
INSERT INTO COURSE (cid, cname) VALUES(173,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(174,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(175,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(176,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(177,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(178,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(179,'Music')
INSERT INTO COURSE (cid, cname) VALUES(180,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(181,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(182,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(183,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(184,'History')
INSERT INTO COURSE (cid, cname) VALUES(185,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(186,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(187,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(188,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(189,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(190,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(191,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(192,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(193,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(194,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(195,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(196,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(197,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(198,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(199,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(200,'History')
INSERT INTO COURSE (cid, cname) VALUES(201,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(202,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(203,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(204,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(205,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(206,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(207,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(208,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(209,'German')
INSERT INTO COURSE (cid, cname) VALUES(210,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(211,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(212,'Music')
INSERT INTO COURSE (cid, cname) VALUES(213,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(214,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(215,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(216,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(217,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(218,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(219,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(220,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(221,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(222,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(223,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(224,'Science')
INSERT INTO COURSE (cid, cname) VALUES(225,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(226,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(227,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(228,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(229,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(230,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(231,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(232,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(233,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(234,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(235,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(236,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(237,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(238,'Art')
INSERT INTO COURSE (cid, cname) VALUES(239,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(240,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(241,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(242,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(243,'History')
INSERT INTO COURSE (cid, cname) VALUES(244,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(245,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(246,'Science')
INSERT INTO COURSE (cid, cname) VALUES(247,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(248,'Science')
INSERT INTO COURSE (cid, cname) VALUES(249,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(250,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(251,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(252,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(253,'German')
INSERT INTO COURSE (cid, cname) VALUES(254,'History')
INSERT INTO COURSE (cid, cname) VALUES(255,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(256,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(257,'History')
INSERT INTO COURSE (cid, cname) VALUES(258,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(259,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(260,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(261,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(262,'French')
INSERT INTO COURSE (cid, cname) VALUES(263,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(264,'History')
INSERT INTO COURSE (cid, cname) VALUES(265,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(266,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(267,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(268,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(269,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(270,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(271,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(272,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(273,'Science')
INSERT INTO COURSE (cid, cname) VALUES(274,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(275,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(276,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(277,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(278,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(279,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(280,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(281,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(282,'Health')
INSERT INTO COURSE (cid, cname) VALUES(283,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(284,'History')
INSERT INTO COURSE (cid, cname) VALUES(285,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(286,'French')
INSERT INTO COURSE (cid, cname) VALUES(287,'Science')
INSERT INTO COURSE (cid, cname) VALUES(288,'Health')
INSERT INTO COURSE (cid, cname) VALUES(289,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(290,'History')
INSERT INTO COURSE (cid, cname) VALUES(291,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(292,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(293,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(294,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(295,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(296,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(297,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(298,'Art')
INSERT INTO COURSE (cid, cname) VALUES(299,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(300,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(301,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(302,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(303,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(304,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(305,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(306,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(307,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(308,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(309,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(310,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(311,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(312,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(313,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(314,'German')
INSERT INTO COURSE (cid, cname) VALUES(315,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(316,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(317,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(318,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(319,'History')
INSERT INTO COURSE (cid, cname) VALUES(320,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(321,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(322,'Health')
INSERT INTO COURSE (cid, cname) VALUES(323,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(324,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(325,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(326,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(327,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(328,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(329,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(330,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(331,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(332,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(333,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(334,'Music')
INSERT INTO COURSE (cid, cname) VALUES(335,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(336,'French')
INSERT INTO COURSE (cid, cname) VALUES(337,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(338,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(339,'French')
INSERT INTO COURSE (cid, cname) VALUES(340,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(341,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(342,'German')
INSERT INTO COURSE (cid, cname) VALUES(343,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(344,'History')
INSERT INTO COURSE (cid, cname) VALUES(345,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(346,'Health')
INSERT INTO COURSE (cid, cname) VALUES(347,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(348,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(349,'German')
INSERT INTO COURSE (cid, cname) VALUES(350,'Health')
INSERT INTO COURSE (cid, cname) VALUES(351,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(352,'German')
INSERT INTO COURSE (cid, cname) VALUES(353,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(354,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(355,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(356,'German')
INSERT INTO COURSE (cid, cname) VALUES(357,'Art')
INSERT INTO COURSE (cid, cname) VALUES(358,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(359,'German')
INSERT INTO COURSE (cid, cname) VALUES(360,'Health')
INSERT INTO COURSE (cid, cname) VALUES(361,'German')
INSERT INTO COURSE (cid, cname) VALUES(362,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(363,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(364,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(365,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(366,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(367,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(368,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(369,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(370,'Health')
INSERT INTO COURSE (cid, cname) VALUES(371,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(372,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(373,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(374,'Music')
INSERT INTO COURSE (cid, cname) VALUES(375,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(376,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(377,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(378,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(379,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(380,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(381,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(382,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(383,'Health')
INSERT INTO COURSE (cid, cname) VALUES(384,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(385,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(386,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(387,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(388,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(389,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(390,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(391,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(392,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(393,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(394,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(395,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(396,'Art')
INSERT INTO COURSE (cid, cname) VALUES(397,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(398,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(399,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(400,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(401,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(402,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(403,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(404,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(405,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(406,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(407,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(408,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(409,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(410,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(411,'French')
INSERT INTO COURSE (cid, cname) VALUES(412,'German')
INSERT INTO COURSE (cid, cname) VALUES(413,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(414,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(415,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(416,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(417,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(418,'French')
INSERT INTO COURSE (cid, cname) VALUES(419,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(420,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(421,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(422,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(423,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(424,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(425,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(426,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(427,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(428,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(429,'French')
INSERT INTO COURSE (cid, cname) VALUES(430,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(431,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(432,'German')
INSERT INTO COURSE (cid, cname) VALUES(433,'Health')
INSERT INTO COURSE (cid, cname) VALUES(434,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(435,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(436,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(437,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(438,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(439,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(440,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(441,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(442,'History')
INSERT INTO COURSE (cid, cname) VALUES(443,'Health')
INSERT INTO COURSE (cid, cname) VALUES(444,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(445,'Music')
INSERT INTO COURSE (cid, cname) VALUES(446,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(447,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(448,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(449,'Music')
INSERT INTO COURSE (cid, cname) VALUES(450,'Health')
INSERT INTO COURSE (cid, cname) VALUES(451,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(452,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(453,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(454,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(455,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(456,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(457,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(458,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(459,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(460,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(461,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(462,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(463,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(464,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(465,'Science')
INSERT INTO COURSE (cid, cname) VALUES(466,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(467,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(468,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(469,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(470,'Health')
INSERT INTO COURSE (cid, cname) VALUES(471,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(472,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(473,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(474,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(475,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(476,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(477,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(478,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(479,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(480,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(481,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(482,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(483,'Health')
INSERT INTO COURSE (cid, cname) VALUES(484,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(485,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(486,'Health')
INSERT INTO COURSE (cid, cname) VALUES(487,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(488,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(489,'French')
INSERT INTO COURSE (cid, cname) VALUES(490,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(491,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(492,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(493,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(494,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(495,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(496,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(497,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(498,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(499,'History')
INSERT INTO COURSE (cid, cname) VALUES(500,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(501,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(502,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(503,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(504,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(505,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(506,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(507,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(508,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(509,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(510,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(511,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(512,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(513,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(514,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(515,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(516,'German')
INSERT INTO COURSE (cid, cname) VALUES(517,'Health')
INSERT INTO COURSE (cid, cname) VALUES(518,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(519,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(520,'French')
INSERT INTO COURSE (cid, cname) VALUES(521,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(522,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(523,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(524,'French')
INSERT INTO COURSE (cid, cname) VALUES(525,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(526,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(527,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(528,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(529,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(530,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(531,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(532,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(533,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(534,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(535,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(536,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(537,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(538,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(539,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(540,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(541,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(542,'Health')
INSERT INTO COURSE (cid, cname) VALUES(543,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(544,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(545,'Science')
INSERT INTO COURSE (cid, cname) VALUES(546,'French')
INSERT INTO COURSE (cid, cname) VALUES(547,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(548,'Science')
INSERT INTO COURSE (cid, cname) VALUES(549,'German')
INSERT INTO COURSE (cid, cname) VALUES(550,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(551,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(552,'History')
INSERT INTO COURSE (cid, cname) VALUES(553,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(554,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(555,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(556,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(557,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(558,'Music')
INSERT INTO COURSE (cid, cname) VALUES(559,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(560,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(561,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(562,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(563,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(564,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(565,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(566,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(567,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(568,'History')
INSERT INTO COURSE (cid, cname) VALUES(569,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(570,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(571,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(572,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(573,'History')
INSERT INTO COURSE (cid, cname) VALUES(574,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(575,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(576,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(577,'Health')
INSERT INTO COURSE (cid, cname) VALUES(578,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(579,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(580,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(581,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(582,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(583,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(584,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(585,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(586,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(587,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(588,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(589,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(590,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(591,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(592,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(593,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(594,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(595,'French')
INSERT INTO COURSE (cid, cname) VALUES(596,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(597,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(598,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(599,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(600,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(601,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(602,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(603,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(604,'History')
INSERT INTO COURSE (cid, cname) VALUES(605,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(606,'History')
INSERT INTO COURSE (cid, cname) VALUES(607,'Art')
INSERT INTO COURSE (cid, cname) VALUES(608,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(609,'History')
INSERT INTO COURSE (cid, cname) VALUES(610,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(611,'Science')
INSERT INTO COURSE (cid, cname) VALUES(612,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(613,'Art')
INSERT INTO COURSE (cid, cname) VALUES(614,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(615,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(616,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(617,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(618,'History')
INSERT INTO COURSE (cid, cname) VALUES(619,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(620,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(621,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(622,'German')
INSERT INTO COURSE (cid, cname) VALUES(623,'French')
INSERT INTO COURSE (cid, cname) VALUES(624,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(625,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(626,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(627,'Science')
INSERT INTO COURSE (cid, cname) VALUES(628,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(629,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(630,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(631,'Art')
INSERT INTO COURSE (cid, cname) VALUES(632,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(633,'Music')
INSERT INTO COURSE (cid, cname) VALUES(634,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(635,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(636,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(637,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(638,'Music')
INSERT INTO COURSE (cid, cname) VALUES(639,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(640,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(641,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(642,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(643,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(644,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(645,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(646,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(647,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(648,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(649,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(650,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(651,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(652,'Health')
INSERT INTO COURSE (cid, cname) VALUES(653,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(654,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(655,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(656,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(657,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(658,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(659,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(660,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(661,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(662,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(663,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(664,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(665,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(666,'History')
INSERT INTO COURSE (cid, cname) VALUES(667,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(668,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(669,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(670,'History')
INSERT INTO COURSE (cid, cname) VALUES(671,'Art')
INSERT INTO COURSE (cid, cname) VALUES(672,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(673,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(674,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(675,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(676,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(677,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(678,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(679,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(680,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(681,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(682,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(683,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(684,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(685,'French')
INSERT INTO COURSE (cid, cname) VALUES(686,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(687,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(688,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(689,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(690,'German')
INSERT INTO COURSE (cid, cname) VALUES(691,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(692,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(693,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(694,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(695,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(696,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(697,'Art')
INSERT INTO COURSE (cid, cname) VALUES(698,'French')
INSERT INTO COURSE (cid, cname) VALUES(699,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(700,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(701,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(702,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(703,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(704,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(705,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(706,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(707,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(708,'French')
INSERT INTO COURSE (cid, cname) VALUES(709,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(710,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(711,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(712,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(713,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(714,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(715,'Art')
INSERT INTO COURSE (cid, cname) VALUES(716,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(717,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(718,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(719,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(720,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(721,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(722,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(723,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(724,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(725,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(726,'French')
INSERT INTO COURSE (cid, cname) VALUES(727,'Science')
INSERT INTO COURSE (cid, cname) VALUES(728,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(729,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(730,'German')
INSERT INTO COURSE (cid, cname) VALUES(731,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(732,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(733,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(734,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(735,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(736,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(737,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(738,'French')
INSERT INTO COURSE (cid, cname) VALUES(739,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(740,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(741,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(742,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(743,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(744,'Health')
INSERT INTO COURSE (cid, cname) VALUES(745,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(746,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(747,'German')
INSERT INTO COURSE (cid, cname) VALUES(748,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(749,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(750,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(751,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(752,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(753,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(754,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(755,'Science')
INSERT INTO COURSE (cid, cname) VALUES(756,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(757,'History')
INSERT INTO COURSE (cid, cname) VALUES(758,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(759,'Health')
INSERT INTO COURSE (cid, cname) VALUES(760,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(761,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(762,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(763,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(764,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(765,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(766,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(767,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(768,'French')
INSERT INTO COURSE (cid, cname) VALUES(769,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(770,'French')
INSERT INTO COURSE (cid, cname) VALUES(771,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(772,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(773,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(774,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(775,'Music')
INSERT INTO COURSE (cid, cname) VALUES(776,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(777,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(778,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(779,'History')
INSERT INTO COURSE (cid, cname) VALUES(780,'Science')
INSERT INTO COURSE (cid, cname) VALUES(781,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(782,'French')
INSERT INTO COURSE (cid, cname) VALUES(783,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(784,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(785,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(786,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(787,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(788,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(789,'French')
INSERT INTO COURSE (cid, cname) VALUES(790,'Art')
INSERT INTO COURSE (cid, cname) VALUES(791,'German')
INSERT INTO COURSE (cid, cname) VALUES(792,'Health')
INSERT INTO COURSE (cid, cname) VALUES(793,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(794,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(795,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(796,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(797,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(798,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(799,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(800,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(801,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(802,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(803,'Art')
INSERT INTO COURSE (cid, cname) VALUES(804,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(805,'History')
INSERT INTO COURSE (cid, cname) VALUES(806,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(807,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(808,'French')
INSERT INTO COURSE (cid, cname) VALUES(809,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(810,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(811,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(812,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(813,'History')
INSERT INTO COURSE (cid, cname) VALUES(814,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(815,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(816,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(817,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(818,'French')
INSERT INTO COURSE (cid, cname) VALUES(819,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(820,'Health')
INSERT INTO COURSE (cid, cname) VALUES(821,'French')
INSERT INTO COURSE (cid, cname) VALUES(822,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(823,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(824,'Grammar')
INSERT INTO COURSE (cid, cname) VALUES(825,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(826,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(827,'Health')
INSERT INTO COURSE (cid, cname) VALUES(828,'German')
INSERT INTO COURSE (cid, cname) VALUES(829,'History')
INSERT INTO COURSE (cid, cname) VALUES(830,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(831,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(832,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(833,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(834,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(835,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(836,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(837,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(838,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(839,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(840,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(841,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(842,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(843,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(844,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(845,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(846,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(847,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(848,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(849,'Science')
INSERT INTO COURSE (cid, cname) VALUES(850,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(851,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(852,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(853,'German')
INSERT INTO COURSE (cid, cname) VALUES(854,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(855,'History')
INSERT INTO COURSE (cid, cname) VALUES(856,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(857,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(858,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(859,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(860,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(861,'German')
INSERT INTO COURSE (cid, cname) VALUES(862,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(863,'History')
INSERT INTO COURSE (cid, cname) VALUES(864,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(865,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(866,'Art')
INSERT INTO COURSE (cid, cname) VALUES(867,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(868,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(869,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(870,'Art')
INSERT INTO COURSE (cid, cname) VALUES(871,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(872,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(873,'Health')
INSERT INTO COURSE (cid, cname) VALUES(874,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(875,'Science')
INSERT INTO COURSE (cid, cname) VALUES(876,'Art')
INSERT INTO COURSE (cid, cname) VALUES(877,'Health')
INSERT INTO COURSE (cid, cname) VALUES(878,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(879,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(880,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(881,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(882,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(883,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(884,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(885,'Music')
INSERT INTO COURSE (cid, cname) VALUES(886,'Basic Math')
INSERT INTO COURSE (cid, cname) VALUES(887,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(888,'Science')
INSERT INTO COURSE (cid, cname) VALUES(889,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(890,'Health')
INSERT INTO COURSE (cid, cname) VALUES(891,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(892,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(893,'German')
INSERT INTO COURSE (cid, cname) VALUES(894,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(895,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(896,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(897,'Music')
INSERT INTO COURSE (cid, cname) VALUES(898,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(899,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(900,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(901,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(902,'Speech')
INSERT INTO COURSE (cid, cname) VALUES(903,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(904,'Science')
INSERT INTO COURSE (cid, cname) VALUES(905,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(906,'Handwriting')
INSERT INTO COURSE (cid, cname) VALUES(907,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(908,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(909,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(910,'Music')
INSERT INTO COURSE (cid, cname) VALUES(911,'Health')
INSERT INTO COURSE (cid, cname) VALUES(912,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(913,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(914,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(915,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(916,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(917,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(918,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(919,'Instrumental Music')
INSERT INTO COURSE (cid, cname) VALUES(920,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(921,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(922,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(923,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(924,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(925,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(926,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(927,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(928,'Music')
INSERT INTO COURSE (cid, cname) VALUES(929,'Music')
INSERT INTO COURSE (cid, cname) VALUES(930,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(931,'Health')
INSERT INTO COURSE (cid, cname) VALUES(932,'Health')
INSERT INTO COURSE (cid, cname) VALUES(933,'Art')
INSERT INTO COURSE (cid, cname) VALUES(934,'Art')
INSERT INTO COURSE (cid, cname) VALUES(935,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(936,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(937,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(938,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(939,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(940,'Music')
INSERT INTO COURSE (cid, cname) VALUES(941,'Dramatics')
INSERT INTO COURSE (cid, cname) VALUES(942,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(943,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(944,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(945,'Art')
INSERT INTO COURSE (cid, cname) VALUES(946,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(947,'French')
INSERT INTO COURSE (cid, cname) VALUES(948,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(949,'Music')
INSERT INTO COURSE (cid, cname) VALUES(950,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(951,'Music')
INSERT INTO COURSE (cid, cname) VALUES(952,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(953,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(954,'French')
INSERT INTO COURSE (cid, cname) VALUES(955,'Design and technology')
INSERT INTO COURSE (cid, cname) VALUES(956,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(957,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(958,'Science')
INSERT INTO COURSE (cid, cname) VALUES(959,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(960,'Spanish')
INSERT INTO COURSE (cid, cname) VALUES(961,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(962,'Physical Education')
INSERT INTO COURSE (cid, cname) VALUES(963,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(964,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(965,'Trigonometry')
INSERT INTO COURSE (cid, cname) VALUES(966,'Art')
INSERT INTO COURSE (cid, cname) VALUES(967,'Earth Science')
INSERT INTO COURSE (cid, cname) VALUES(968,'Resource Program')
INSERT INTO COURSE (cid, cname) VALUES(969,'Sociology')
INSERT INTO COURSE (cid, cname) VALUES(970,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(971,'French')
INSERT INTO COURSE (cid, cname) VALUES(972,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(973,'Ancient Civilizations')
INSERT INTO COURSE (cid, cname) VALUES(974,'French')
INSERT INTO COURSE (cid, cname) VALUES(975,'Latin')
INSERT INTO COURSE (cid, cname) VALUES(976,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(977,'Science')
INSERT INTO COURSE (cid, cname) VALUES(978,'Accounting')
INSERT INTO COURSE (cid, cname) VALUES(979,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(980,'Music')
INSERT INTO COURSE (cid, cname) VALUES(981,'French')
INSERT INTO COURSE (cid, cname) VALUES(982,'Modern Literature')
INSERT INTO COURSE (cid, cname) VALUES(983,'Art')
INSERT INTO COURSE (cid, cname) VALUES(984,'Mathematics')
INSERT INTO COURSE (cid, cname) VALUES(985,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(986,'Language Arts')
INSERT INTO COURSE (cid, cname) VALUES(987,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(988,'Economics')
INSERT INTO COURSE (cid, cname) VALUES(989,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(990,'French')
INSERT INTO COURSE (cid, cname) VALUES(991,'Health')
INSERT INTO COURSE (cid, cname) VALUES(992,'Leadership')
INSERT INTO COURSE (cid, cname) VALUES(993,'English IV')
INSERT INTO COURSE (cid, cname) VALUES(994,'Geography')
INSERT INTO COURSE (cid, cname) VALUES(995,'American Literature')
INSERT INTO COURSE (cid, cname) VALUES(996,'German')
INSERT INTO COURSE (cid, cname) VALUES(997,'Ecology')
INSERT INTO COURSE (cid, cname) VALUES(998,'LOGIC')
INSERT INTO COURSE (cid, cname) VALUES(999,'History')
INSERT INTO COURSE (cid, cname) VALUES(1000,'Handwriting')